name: CI/CD Publish Powershel Module on Powershell Gallery

on:
  push:
    branches:
      - main
      - "feature/**"

jobs:
  tests-and-analyse:
    runs-on: ubuntu-latest
    environment: publish
    # container:
    #   image: mcr.microsoft.com/powershell:7.5-debian-bookworm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Necessary Modules
        shell: pwsh
        run: |
          Install-Module -Name Pester -RequiredVersion 5.3.1 -Force
          Install-Module -Name InvokeBuild -RequiredVersion 5.9.11 -Force

      - name: Tests
        shell: pwsh
        run: |
          Set-Location ./src
          Invoke-Build Feature-Test

  publish-job:
    if: github.ref == 'refs/heads/main'
    needs: tests-and-analyse
    runs-on: ubuntu-latest
    environment: publish
    env:
      NUGET_API_KEY_A: ${{ secrets.NUGETAPIKEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Necessary Modules
        shell: pwsh
        run: |
          Install-Module -Name Pester -RequiredVersion 5.3.1 -Force
          Install-Module -Name InvokeBuild -RequiredVersion 5.9.11 -Force

      - name: Publish
        shell: pwsh
        run: |
          Set-Location ./src
          Invoke-Build Release
